name: Microsoft E5 Auto Renewal

on:
  schedule:
    - cron: '0 */6 * * *'  # Chạy mỗi 6 tiếng
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  renewal:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run E5 Auto Renewal
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
      run: |
        python main.py
